### ISSUE TITLE
avoid unnecessarily converting address manually

### ISSUE THREAD

**Issue by RetricSu** [nervosnetwork/layer2-evm-documentation#2]
given that this will be the first station for developer to learn about layer2 EVM, I think it is extremely important to show the developer the prefer and right way to use polyjuice-provider. 

in the docs, developers should pass ABI(multiple ABIs also supported) to provider and let provider do the address-converting instead of converting address by themself. 

here is why:

converting ethAddress to polyjuiceAddress is kind of complex, we have 4 types of address:

id | type      |  already created ? | has account id and account script hash in godwoken ?
| -----------| ----------- | ----------- | ----------- |
|1 | EOA      | ☑️       |  ☑️ 
|2 | EOA   |  ✖️        |✖️  
|3 | contract      | ☑️       |  ☑️ 
|4 | contract   |  ✖️        |✖️  

> 1. eoa address which already been created on chain, has account_id and account script hash in godwoken
> 2. eoa address which haven't been created on chain, has no account_id and no account script hash in godwoken
> 3. contract address which already been created on chain, has account_id and account script hash in godwoken (here [actually](https://github.com/nervosnetwork/godwoken-polyjuice/blob/main/docs/EVM-compatible.md#different-address-type) the `contractAddress = script_hash.slice(0, 42)` )
> 4. contract address which haven't been created on chain ([create2](https://docs.openzeppelin.com/cli/2.8/deploying-with-create2)), has no account_id and no account script hash in godwoken
> 
> ref: https://github.com/nervosnetwork/godwoken-polyjuice/blob/main/docs/EVM-compatible.md#different-address-type

for converting address, there are actually two parts of it:

1. convert `eth address => polyjuice address` in `eth_tx's input data` when sending transaction

 ```js
const eth_tx = {
    from: "....",
    to: "....",
    gas: "...",
    gasPrice: "...",
    value: "...",
    data: "<here we convert the address parameter if it has one>"
}
 ```
 2. convert back `polyjuice address => eth address` when calling contract method contains address type in return

```js
const address = contract.methods.call_method_to_return_address();
// here the address should be eth address converting from polyjuice address
```

now let's consider this edge case:

if you have No.2 type address, which is eoa address haven't been created on chain:

of course you can convert the eth address to polyjuice address manually using libary like `nervos-godwoken-integration`, but you can not convert it back to eth address after, because the eoa address has no script hash on chain, you can't query it from godwoken. in your dapp you have to find a way to save the `polyjuiceAddress-ethAddress` mapping some where for querying later. 

the reason that provider can handle such case is because it already done such thing. the mapping is stored in godwoken-web3 if provider encounter any eoa address which has not been created on chain. but if you don't pass ABI Items and let it convert for you, it won't be able to save those address mapping either. 

so I think manually converting the address will require a lot of extra works for dapp developer, and it is not really the way we want people to handle with provider. 

last thing, 

ideally the two converting process above, should both deal with any one of 4 types address correctly. but there are still some limits, I have describe the limitations in [provider's docs](https://github.com/nervosnetwork/polyjuice-provider/blob/main/docs/known-caveats.md). 

in short, right now we (1. don't support create2 address which has not been created on chain passing as `eth_tx's input data`(No.4 type address). and (2. don't support deployment for converting address in contract constructor arguments.( this one might be solved in the future as developing the provider library)

it is such a great job that the docs here brings up the difference for address and even showcase how we can converting the address manually, because right now in some edge case(like deployment), it really needs. but in most of time, when developer are interacting with smart-contract, they should leave the work to providers. 

so I think it will be better if we can implement the following:

- [ ] in example code, when interacting with smart-contract,  it will be better if we [pass abiItem](https://github.com/nervosnetwork/layer2-evm-documentation/pull/1) to `polyjuiceConfig` by default to remind people leaving the work to providers.
- [ ] avoid manually converting address, if unnecessary, as much as possible
- [ ] give a short description that provdier has some limitations, guide developer to read [known-caveats](https://github.com/nervosnetwork/polyjuice-provider/blob/main/docs/known-caveats.md).

and provider repo can also quoting this docs and redirect developer to learn from here too.

cc @Kuzirashi

**Comment by jjyr** [comment]
We should always pass the abiItems when we interact or deploy with contract, otherwise the developers will meet inconsistent in the layer2 contract.

**Comment by e00dan** [comment]
I included setting multiple ABI code fragment in all the most important code examples. 👍

**Comment by e00dan** [comment]
Does not apply anymore since new version of Godwoken uses native Ethereum addresses.
