### ISSUE TITLE
support deployment arguments address converting when deploy contract

### ISSUE THREAD

**Issue by RetricSu** [nervosnetwork/layer2-evm-documentation#3]
since [0.1.3](https://github.com/nervosnetwork/polyjuice-provider/blob/main/docs/get-started.md#example-deploy-contract) provider support [deployment arguments address converting](https://github.com/nervosnetwork/polyjuice-provider/blob/main/docs/known-caveats.md#short-version) when deploying contracts, can we update the code examples as well?  one important note is that using `addressTranslator` to convert address here is discouraged as I mention in this [issue](https://github.com/nervosnetwork/layer2-evm-documentation/issues/2) it has some edge case. @Kuzirashi

**Comment by e00dan** [comment]
Does not apply anymore since new version of Godwoken uses native Ethereum addresses.
